; PlatformIO Project Configuration File
;
;   Build options: build flags, source filter
;   Upload options: custom upload port, speed and extra flags
;   Library options: dependencies, extra library storages
;   Advanced options: extra scripting
;
; Please visit documentation for the other options and examples
; https://docs.platformio.org/page/projectconf.html

[env:canh_tay]
platform = espressif32
board = esp32dev
framework = arduino
lib_deps =
	adafruit/Adafruit PWM Servo Driver Library
	bblanchon/ArduinoJson
	knolleary/PubSubClient
	links2004/WebSockets
src_filter =
	+<main_canh_tay.cpp>
	+<app_context.h>
	+<canh_tay/>
	+<network/>
	+<web/>
	+<dongco/>
	+<quat_hut/>
	-<xe/>
	-<main.cpp>
	-<main_xe.cpp>

[env:xe_node]
platform = espressif32
board = esp32dev
framework = arduino
lib_deps =
	rfetick/MPU6050_light
src_filter =
	+<main_xe.cpp>
	+<app_context.h>
	+<xe/>
	-<canh_tay/>
	-<network/>
	-<web/>
	-<dongco/>
	-<quat_hut/>
	-<main.cpp>
	-<main_canh_tay.cpp>


